name: release_develop
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  open_release:
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    outputs:
      release_id: ${{steps.create_keygen_release.outputs.result}}
    steps:
      - id: create_keygen_release
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const response = await fetch("https://api.keygen.sh/v1/accounts/${{ secrets.KEYGEN_ACCOUNT }}/releases", {
              method: "POST",
              headers: {
                "Authorization": "Bearer ${{ secrets.KEYGEN_AUTH }}",
                "Content-Type": "application/vnd.api+json",
                "Accept": "application/vnd.api+json"
              },
              body: JSON.stringify({
                "data": {
                  "type": "release",
                  "attributes": {
                    "version": "${{github.ref_name}}".replace('v',''),
                    "channel": "stable",
                    "tag": "${{ github.ref_name }}"
                  },
                  "relationships": {
                    "product": {
                      "data": {
                        "type": "product",
                        "id": "${{secrets.KEYGEN_PRODUCT_ID}}"
                      }
                    },
                    "package": {
                      "data": {
                        "type": "package",
                        "id": "${{secrets.KEYGEN_PACKAGE_ID}}"
                      }
                    }
                  }
                }
              })
            })
            const { data, errors } = await response.json()
            console.log(errors)
            console.log(data)
            return data.id
  build:
    needs: open_release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    outputs:
      files: ${{steps.build_app.outputs.artifactPaths}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libgtk-3-dev \
          libgtk-3-0
      #      - name: Install dependencies (Windows only)
      #        if: matrix.platform == 'windows-latest'
      #        run: |
      #          vcpkg install openssl
      #          vcpkg install sqlite3
      - name: Install dependencies (Macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install vips cmake

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: setup Diesel shemas
        working-directory: ./src-tauri
        run: |
          cargo install diesel_cli --no-default-features --features "sqlite-bundled"
          diesel migration generate --diff-schema schema.rs

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: yarn install

      - id: build_app
        name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SECRET_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          #          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          #          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          CI: true
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "mxm fleet management v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false

      - id: filter_gh_artifact
        name: filter GH artifacts
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: json
          script: |
            const files = ${{steps.build_app.outputs.artifactPaths}} || []
            const file_list = files.join("\n");
            const file_path = file_list.match(/^(?!.*\.sig$).*\.(gz|msi|AppImage)$/gm)[0];

             const file_name = file_path.match(/([^/|\\]+)$/gm)[0];

             const file_sig = file_list.match(/^(?!.*\.msi.*)(.*\.sig)$/gm)[0];

             const file_os = file_path
               .match(/macos|AppImage|msi/g)[0]
               .replace(/macos|AppImage|msi/g, (match) => {
                 if (match == "macos") return "darwin";
                 if (match == "AppImage") return "linux";
                 if (match == "msi") return "windows";
                 return match;
               });
             const file_arch = file_path
               .match(/macos|AppImage|msi/g)[0]
               .replace(/macos|AppImage|msi/g, (match) => {
                 if (match == "macos") return "aarch64";
                 if (match == "AppImage" || match == "msi") return "x86_64";
                 return match;
               });

             const file_type = file_name.match(/([^.]+)$/gm)[0];
             return {file_name: file_name, file_path: file_path, file_sig: file_sig, file_os: file_os, file_arch: file_arch, file_type: file_type};

      - id: create_file_checksum
        name: Create File checksum
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const crypto = require('crypto')
            const {file_path} = ${{ steps.filter_gh_artifact.outputs.result }}
            const file_content = fs.readFileSync(file_path)
            const hash = crypto.createHash('sha512');
            hash.update(file_content);
            const digest_buffer = hash.digest();
            const base64_digest = digest_buffer.toString('base64');
            return base64_digest;

      - id: create_keygen_artifact
        name: create keygen artifact
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const {file_name, file_path, file_os, file_arch, file_sig, file_type} = ${{ steps.filter_gh_artifact.outputs.result }}
            const file_signature = fs.readFileSync(file_sig, "utf-8")
            const file_info = fs.statSync(file_path)
            const response = await fetch("https://api.keygen.sh/v1/accounts/${{ secrets.KEYGEN_ACCOUNT }}/artifacts", {
              redirect: "manual",
              method: "POST",
              headers: {
                "Authorization": "Bearer ${{ secrets.KEYGEN_AUTH }}",
                "Content-Type": "application/vnd.api+json",
                "Accept": "application/vnd.api+json"
              },
              body: JSON.stringify({
                "data": {
                  "type": "artifact",
                  "attributes": {
                    "filename": file_name,
                    "platform": file_os,
                    "arch": file_arch,
                    "filetype": file_type,
                    "signature": file_signature,
                    "checksum": "${{ steps.create_file_checksum.outputs.result }}",
                    "filesize": file_info.size
                  },
                  "relationships": {
                    "release": {
                      "data": {
                        "type": "release",
                        "id": "${{ needs.open_release.outputs.release_id }}"
                      }
                    }
                  }
                }
              })
            })
            const { data, errors } = await response.json()
            console.log(errors)
            console.log(data);
            return data.links.redirect

      - id: upload_keygen_artifact
        name: upload artifact to keygen
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const {file_path} = ${{steps.filter_gh_artifact.outputs.result}}
            const file_data =  fs.createReadStream(file_path)
            const file_info = fs.statSync(file_path)
            const response = await fetch( "${{steps.create_keygen_artifact.outputs.result}}" , {
              method: "PUT",
              headers: {
                "Content-Length": file_info.size
              },
              body: file_data
            })
            console.log(response)

  publish:
    permissions:
      contents: write
    needs:
      - build
      - open_release
    runs-on: "ubuntu-latest"
    steps:
      - id: publish_release
        name: Publish keygen release
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          script: |
            const response = await fetch("https://api.keygen.sh/v1/accounts/${{ secrets.KEYGEN_ACCOUNT }}/releases/${{ needs.open_release.outputs.release_id }}/actions/publish", {
              method: "POST",
              headers: {
                  "Accept": "application/vnd.api+json",
                  "Authorization": "Bearer ${{ secrets.KEYGEN_AUTH }}",
              }
            })
            console.log(response)
